#!/bin/bash

launcher() {
    LOCK_FILE_LAUNCHER="$HOME/.cache/eww-launcher.lock"

run() {
    eww open launchermenu -c ~/Documents/eww/bar/
}

# Open widgets
if [[ ! -f "$LOCK_FILE_LAUNCHER" ]]; then
    eww close launchermenu -c ~/Documents/eww/bar/
    touch "$LOCK_FILE_LAUNCHER"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_LAUNCHER" ]]; then
    eww close launchermenu -c ~/Documents/eww/bar/
    rm "$LOCK_FILE_LAUNCHER" && echo "closed"
fi
}

launcher